name: Build release

on:
  pull_request:
    types: closed
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Decrypt release secret
      run: ./.github/scripts/decrypt_key.sh
      env:
        RELEASE_PASSPHRASE: ${{ secrets.RELEASE_PASSPHRASE }}
        GOOGLE_PASSPHRASE: ${{ secrets.GOOGLE_PASSPHRASE }}
        PROPERTIES_PASSPHRASE: ${{ secrets.PROPERTIES_PASSPHRASE }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release
      run: ./gradlew assembleRelease
    
    - name: Extract compared branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${{ github.head_ref }} | cut -d'/' -f 2)"
    
    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.BRANCH_NAME }}
        release_name: Release ${{ env.BRANCH_NAME }}
        draft: false
        prerelease: false
    
    - name: Upload Release Application
      id: upload-app-release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/app-release.apk
        asset_name: my-pet-care.apk
        asset_content_type: application/vnd.android.package-archive
