name: Instrumentation tests

on:
  push:
    branches-ignore: [ master, develop ]
      
  pull_request:
    types: opened
    branches: [ master, develop ]

jobs:
  tests:
    
    runs-on: macos-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    - name: Decrypt release secret
      run: ./.github/scripts/decrypt_key.sh
      env:
        GOOGLE_PASSPHRASE: ${{ secrets.GOOGLE_PASSPHRASE }}
        RELEASE_PASSPHRASE: ${{ secrets.RELEASE_PASSPHRASE }}
        PROPERTIES_PASSPHRASE: ${{ secrets.PROPERTIES_PASSPHRASE }}

    - name: grant execution to gradlew
      run: chmod +x ./gradlew
    
    - name: run instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 23
        script: ./gradlew connectedCheck  
    
    - name: get intrumentation coverage file name
      run: ls app/build/outputs/code_coverage/debugAndroidTest/connected/
