name: Android CI

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  test report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Coverage Report
      run: |
        chmod +x gradlew
        ./gradlew jacocoTestReport
        export CODACY_PROJECT_TOKEN=${{secrets.CODACY_KEY}}
        bash <(curl -Ls https://coverage.codacy.com/get.sh)
